apiVersion: v1
kind: Namespace
metadata:
  name: vault-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: vault-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vault-demo
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app"
        vault.hashicorp.com/agent-inject-secret-app-config.txt: "db/creds/readonly"
        vault.hashicorp.com/agent-inject-template-app-config.txt: |
        #  {{- with secret "db/creds/readonly" -}}
        #  postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/wizard
        #  {{- end -}}
      labels:
        app: app
    spec:
      serviceAccountName: demo-sa
      containers:
        - name: app
          image: jweissig/app:0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vault-demo
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      serviceAccountName: demo-sa
      containers:
        - name: db
          image: postgres
          envFrom:
          - configMapRef:
              name: postgres-configuration
          ports:
          - containerPort: 5432
            name: postgresdb
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vault-demo
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: vault-demo
  name: postgres-configuration
  labels:
    app: db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

