apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/namespace: "admin"
        vault.hashicorp.com/role: "app2"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/app1/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/app1/config" -}}
          export RESULT="{{ .Data.data.password }}"
          {{- end -}}
      labels:
        app: app2
    spec:
      serviceAccountName: app2
      containers:
        - name: app2
          image: alpine:latest
          args:
            ['sh', '-c', 'source . /vault/secrets/config && sleep 1000']
